Exception Class
odufrn/odufrn-downloader pull request #95
Opened 2019-10-05 22:30 UTC by Physsix27

# Pull Request
`exception.py` es una clase que contiene exception en la cual podemos usar en cualquier lado del projecto.

### Issues Vinculadas:
  - #56  - Totalmente

### Pre-Pull Request Checklist:
> Tienes que tener `requests` instalado antes de correr lo siguiente.
- [x] Corre `python3 tests/_file.py`

2019-10-07 03:41 UTC, Physsix27 commented
Hey @itepifanio, Dejame saber si necesitas algo mas para que resuelva en issue #56, creo que esta completo.

2019-10-07 13:47 UTC, johnazedo approved these changes

2019-10-07 14:00 UTC, itepifanio requested changes
Me gustaria la carpeta (folder) odufrn_exception como` odufrn_downloader/exception `.

En la exception odufrnIoError pass una [default message](https://stackoverflow.com/questions/49224770/default-message-in-custom-exception-python) y quita la mensajem "'odufrIOError: Escribir algo <-- :-)'" en la class File.

2019-10-07 22:36 UTC, Physsix27 commented
quiere que le pongo a `class odufrException(Exception):` ?

```def __init__(self):
         default_message = 'This is a default message!'
         super().__init__(default_message)```

2019-10-07 23:35 UTC, itepifanio commented
> Quieres que quite `pass` de `class odufrException(Exception):` y ponga:
> 
> ```
> def __init__(self):
>          default_message = 'This is a default message!'
>          super().__init__(default_message)
> ```
> 
> ?

Si y una en la custom IOError.

2019-10-08 00:56 UTC, itepifanio approved these changes

2019-10-08 00:57 UTC, merged

2019-10-08 00:57 UTC, itepifanio commented
@Physsix27 Gracias por tu PR!