Resolve #92
odufrn/odufrn-downloader pull request #96
Opened 2019-10-29 23:34 UTC by diegodiogenes

# Pull Request
Resolve a issue #92, implementa o método _get_search_related_package, para acessar o portal de dados abertos da UFRN e buscar os packages relacionados.

- **Issues vinculadas**:
  - #92 - Totalmente

## Principais locais de modificação
- `_get_related_package_search` na classe `Package`
- `search_related` renomeada para `search_similar` em `LevenshteinMixin`

2019-10-30 11:55 UTC, nymarya approved these changes

2019-10-30 11:56 UTC, nymarya commented
@diegodiogenes show, só corrigir os erros do Travis:
```
./odufrn_downloader/modules/Package.py:38:1: W293 blank line contains whitespace
./odufrn_downloader/modules/Package.py:40:55: E226 missing whitespace around arithmetic operator
./build/lib/odufrn_downloader/modules/Package.py:38:1: W293 blank line contains whitespace
./build/lib/odufrn_downloader/modules/Package.py:40:55: E226 missing whitespace around arithmetic operator
```

2019-10-30 17:11 UTC, alvarofpp requested changes

2019-11-01 18:21 UTC, alvarofpp approved these changes

2019-11-01 18:21 UTC, merged